### ISSUE TITLE
Renommer condor.py en csub

### ISSUE THREAD

**Issue by jouvin** [LAL/Condor-Tools#2]
Je trouve que le nom `condor.py` n'est pas très judicieux pour 2 raisons : 
- l'extension `.py` est toujours bizarre dans un nom de commande
- `condor` est un nom un peu trop générique pour qqc qui ne fait que de la soumission

J'ai pas d'idée alternative géniale, je proposerai par example `csub` en echo à `qsub`, `bsub`...

**Comment by guillaume-philippon** [comment]
Fixed by PR #7
